name: GitHub Releases to Discord

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: GitHub Releases to Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "5291001"  # #50BBF9
          username: "OpenDisplay Firmware"
          # avatar_url: "https://raw.githubusercontent.com/OpenDisplay-org/.github/main/profile/logo.png"
          # content: "||@everyone||"
          footer_title: "Firmware Release"
          footer_timestamp: true
          reduce_headings: true
          remove_github_reference_links: false
